#!/bin/bash
output=""
# Checks if any yaml files have been staged
stagedFiles=$(git diff --cached --name-only | egrep "*.yaml")
for file in $stagedFiles
do
	# Validates that the linting is correct
	output+=$(yamllint $file 2>&1)
	exitCode=$?
	if [[ "${exitCode}" == 1 ]]
	then
		# Don't commit if yamllint has errors
		echo "$output"
		echo -e "Fix yaml linting before committing"
		exit 1
	fi
done
