---
# Configuration file for Prettier
#
# Prettier formats my Home Assistant files automatically,
# this makes things look consistently.
#
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    printWidth: 88
    tabWidth: 2
    useTabs: true
