---
- id: enable_zigbee_join
  alias: Enable Zigbee joining
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: "on"
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "true"
    - service: timer.start
      data:
        entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  trigger:
    - entity_id: input_boolean.zigbee_permit_join
      platform: state
      to: "off"
  action:
    - data:
        payload: "false"
        topic: zigbee2mqtt/bridge/config/permit_join
      service: mqtt.publish
    - data:
        entity_id: timer.zigbee_permit_join
      service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "false"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee_permit_join
- id: zigbee2mqtt_create_notification_on_successfull_interview
  alias: Zigbee Device Joined Notification
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/bridge/log
  condition:
    condition: template
    value_template:
      '{{trigger.payload_json.type == "pairing" and trigger.payload_json.message
      == "interview_successful"}}'
  action:
    - service: persistent_notification.create
      data_template:
        title: Device joined the Zigbee2MQTT network
        message: |
          "Name: {{trigger.payload_json.meta.friendly_name}},
          Vendor: {{trigger.payload_json.meta.vendor}},
          Description: {{trigger.payload_json.meta.description}}"
- id: check_scheduled_downtime_on_boot
  alias: Check for scheduled downtime on boot
  description: ""
  trigger:
    - event: start
      platform: homeassistant
  condition:
    - condition: state
      entity_id: calendar.home_assistant_shutdown_schedule
      state: "on"
  action:
    - data: {}
      entity_id: light.all_lights
      service: light.turn_off
    - data: {}
      entity_id: light.entryway
      service: light.turn_off
  mode: single
- id: update_dns_records
  alias: Update DNS records on boot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: cloudflare.update_records
  mode: single
