---
# This integration is a meta-component and configures a default set of
# integrations for Home Assistant to load.
#
# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  currency: NOK
  time_zone: !secret time_zone
  country: "NO"
  external_url: !secret external_url

  packages: !include_dir_named packages

# The logger integration lets you define the level of logging activities in Home Assistant.
#
# https://www.home-assistant.io/integrations/logger/
logger:
  default: warn
  logs:
    homeassistant.helpers.template: error

recorder:
  db_url: !secret maria_db

# Text-to-Speech (TTS) enables Home Assistant to speak to you.
#
# https://www.home-assistant.io/integrations/tts
tts:
  - platform: google_translate

# The script integration allows users to specify a sequence of
# actions to be executed by Home Assistant.
#
# https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml

# You can create scenes that capture the states you want certain entities to be.
#
# https://www.home-assistant.io/integrations/scene/
scene: !include scenes.yaml

# This integration allows you to track and control various light bulbs.
#
# https://www.home-assistant.io/integrations/light/
light: !include light.yaml

input_select: !include input_select.yaml

input_text: !include input_text.yaml

input_boolean: !include input_boolean.yaml

input_button: !include input_button.yaml

input_number: !include input_number.yaml

mqtt: !include mqtt.yaml

command_line: !include command_line.yaml

template: !include templates.yaml
