# This integration is a meta-component and configures a default set of 
# integrations for Home Assistant to load.
#
# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  currency: "NOK"
  time_zone: !secret time_zone

# The logger integration lets you define the level of logging activities in Home Assistant.
#
# https://www.home-assistant.io/integrations/logger/
logger: 
  default: warn
  logs:
    homeassistant.helpers.template: error

recorder:
  db_url: !secret maria_db

# Lovelace is the Home Assistant dashboard. 
# It is a fast, customizable and powerful way for users to manage their 
# home using their mobiles and desktops
# 
# https://www.home-assistant.io/lovelace/
lovelace:
  mode: storage
  dashboards: !include ./lovelace/dashboards.yaml

updater:

python_script:

# The http integration serves all files and data required for the Home Assistant frontend
# 
# https://www.home-assistant.io/integrations/http/
http:
  # Let you set a port to use.
  server_port: !secret http_server_port

  # Path to your TLS/SSL certificate to serve Home Assistant over a secure connection.
  ssl_certificate: !secret http_ssl_certificate

  # Path to your TLS/SSL key to serve Home Assistant over a secure connection.
  ssl_key: !secret http_ssl_key

  # Enable parsing of the X-Forwarded-For header, passing on the client’s 
  # correct IP address in proxied setups.
  use_x_forwarded_for: true

  # List of trusted proxies, consisting of IP addresses or networks, that are 
  # allowed to set the X-Forwarded-For header.
  trusted_proxies: !secret http_trusted_proxies

# Text-to-Speech (TTS) enables Home Assistant to speak to you.
#
# https://www.home-assistant.io/integrations/tts
tts:
  - platform: google_translate

# Groups allow the user to combine multiple entities into one.
#
# https://www.home-assistant.io/integrations/group/
group: !include groups.yaml

# Automations in Home Assistant allow you to automatically respond to things that happen.
#
# https://www.home-assistant.io/docs/automation/
automation: !include automations.yaml

# The script integration allows users to specify a sequence of actions to be executed by Home Assistant.
#
# https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml

# You can create scenes that capture the states you want certain entities to be.
#
# https://www.home-assistant.io/integrations/scene/
scene: !include scenes.yaml

# This integration allows you to track and control various light bulbs.
#
# https://www.home-assistant.io/integrations/light/
light: !include light.yaml


input_select: !include input_select.yaml

input_text: !include input_text.yaml

# This offers the official frontend to control Home Assistant.
#
# https://www.home-assistant.io/integrations/frontend/
frontend:
  # Allow to define different themes.
  themes: !include_dir_merge_named themes

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# The google_assistant integration allows you to control things via Google Assistant on your 
# mobile, tablet or Google Home device.
#
# https://www.home-assistant.io/integrations/google_assistant/
google_assistant:
  # Project ID from the Actions on Google console
  project_id: !secret google_assistant_project_id

  # Service account information.
  service_account: !include service_account.json

  # List of entity domains to expose to Google Assistant if expose_by_default is set to true.
  exposed_domains:
    - group
    - light
    - scene
    - switch
  
  # Entity specific configuration for Google Assistant
  entity_config:
    switch.bedlight_switch:
      expose: false
    switch.erase_omg:
      expose: false
    switch.kiosk_screen:
      expose: false
    switch.restart_omg:
      expose: false
    switch.window_light_switch:
      expose: false
    light.kitchen_1:
      expose: false
    light.kitchen_2:
      expose: false
    light.kitchen_3:
      expose: false
    light.kitchen_4:
      expose: false

notify:
  - platform: html5
    name: Desktop
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret gmail

# The air_quality base platform allows other integrations to process information about 
# air quality and pollution details.
#
# https://www.home-assistant.io/integrations/air_quality/
air_quality:
  # The norway_air integration queries the Norway air quality data feed provided by 
  # the Norwegian Meteorological Institute.
  #
  # https://www.home-assistant.io/integrations/norway_air/
  - platform: norway_air
    forecast: 12

# Sensors are a basic platform component in Home Assistant. 
# They monitor the states and conditions of a variety of entities.
#
# https://www.home-assistant.io/integrations/sensor
sensor:
  - platform: version
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: processor_use
  - platform: command_line
    name: Rasberry pi temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(2) }}"
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  - platform: seventeentrack
    username: !secret email
    password: !secret seventeentrack_password

    # https://www.home-assistant.io/integrations/time_date/
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "time_date"

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  stuff_on_balcony:
    name: Will it rain?
    icon: mdi:weather-pouring
  manual_entryway:
    name: Manual Entryway
    icon: mdi:motion-sensor

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish