---
# This integration is a meta-component and configures a default set of
# integrations for Home Assistant to load.
#
# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  # Sets up basic information in Home Assistant
  #
  # https://www.home-assistant.io/docs/configuration/basic/
  customize: !include customize.yaml
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  currency: NOK
  time_zone: !secret time_zone
  country: "NO"
  external_url: !secret external_url

  # Makes it possible to split the configuration in to
  # smaller chucks that is easier to maintain
  #
  # https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

# Automations in Home Assistant allow you to automatically respond to things that happen.
#
# https://www.home-assistant.io/docs/automation/
automation: !include automations.yaml
automation more: !include_dir_list automations

# The script integration allows users to specify a sequence of
# actions to be executed by Home Assistant.
#
# https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml
script more: !include_dir_list scripts
