---
# This integration is a meta-component and configures a default set of
# integrations for Home Assistant to load.
#
# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  # Sets up basic information in Home Assistant
  #
  # https://www.home-assistant.io/docs/configuration/basic/
  customize: !include customize.yaml
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  currency: NOK
  time_zone: !secret time_zone
  country: "NO"
  external_url: !secret external_url

  # Makes it possible to split the configuration in to
  # smaller chucks that is easier to maintain
  #
  # https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

recorder:
  db_url: !secret maria_db
