---
- platform: switch
  name: Window Light
  entity_id: switch.window_light

- platform: switch
  name: Balcony light
  entity_id: switch.balcony_light

- platform: group
  name: All Lights
  entities:
    - light.living_room_lights
    - light.kitchen_lights

- platform: switch
  name: Christmas Tree
  entity_id: switch.christmas_tree
