---
- platform: group
  name: Living Room Lights
  entities:
    - light.window_light

- platform: switch
  name: Window Light
  entity_id: switch.window_light

- platform: switch
  name: Outside light
  entity_id: switch.outside_light

- platform: group
  name: All Lights
  entities:
    - light.living_room_lights
